### ISSUE TITLE
Map all nationalities from KBR MARC authority records

### ISSUE THREAD

**Issue by SvenLieber** [kbrbe/beltrans-data-integration#75]
In the past we used a CSV dump of KBR authorities. We recently switched to using the MARCXML export for more structured data from which we extract CSV ourselves. We get the nationality from MARC field `370$c`. However, there might be several `370` fields, sometimes just to indicate different languages, for example *Gent* and *Gand*. In such cases we would get two times the nationality. However, multiple nationalities are also expressed like this.

We might get `"be;be;be"` or `"be;fr"` with our extraction script. All these nationalities should be mapped.

**Comment by SvenLieber** [comment]
This likely needs a change in the Python script to create a separate CSV with `contributorID, nationality` because nationality is not always provided. Thus this use case is affected by an existing bug in the used software: https://github.com/RMLio/yarrrml-parser/issues/146

**Comment by AnnVanCamp** [comment]
Dag Sven

Voor de nationaliteit enkel naar 370$c kijken. De andere velden wijzen niet noodzakelijk op de BE nationaliteit. Bv. Julio Cortázar: geboren in Brussel, maar Argentijn of Marguerite Yourcenar: geboren in Brussel, maar Franse.
In de NTA van de KB is die Marguerite Yourcenar wel als BE beschouwd, zag ik, maar voor BELTRANS haar graag wegfilteren wegens Frans.

370

Geassocieerde plaats

$a

Geboorteplaats

Stad en land van geboorte. Volgens formaat : Stad (land).  Bv. Antwerpen (België)
Als enkel land gekend is, de code zetten (bv. ‘be’)

$b

Plaats van overlijden

Stad en land van overlijden. Volgens formaat : Stad (land).  Bv. Antwerpen (België)
Als enkel land gekend is, de code zetten (bv. ‘be’)

$c

Geassocieerd land (nationaliteit)

Nationaliteit of geassocieerd land van de auteur.
Zelfde codes als voor Documenten – 044$a, dus ‘be’, ‘fr’, … cf. landcodes<https://www.loc.gov/marc/countries/countries_code.html>
Bij twijfel of ongekend, ‘xx – No place, unknown, or undetermined’ zetten.

$i

Informatie over de relatie

Als subveld $c ingevuld is, code ‘nat’ voor nationaliteit



Met vriendelijke groeten – Cordialement

Ann Van Camp
Ontwikkeling van de hedendaagse verzamelingen – Développement des collections contemporaines

***@***.******@***.***>
+32 (0)2 519 54 37 – +32 (0)494 62 30 43

Kunstberg 28, B-1000 Brussel
Mont des Arts 28, B-1000 Bruxelles
www.kbr.be<http://www.kbr.be/>

***@***.***<http://www.kbr.be/>

From: Sven Lieber ***@***.***>
Sent: Wednesday, 16 February, 2022 15:52
To: kbrbe/beltrans-data-integration ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kbrbe/beltrans-data-integration] Map all nationalities from KBR MARC authority records (Issue #75)


In the past we used a CSV dump of KBR authorities. We recently switched to using the MARCXML export for more structured data. We get the nationality from MARC field 370$c. However, there might be several 370 fields, sometimes just to indicate different languages, for example Gent and Gand. In such cases we would get two times the nationality. However, multiple nationalities are also expressed like this.

We might get "be;be;be" or "be;fr" with our extraction script. All these nationalities should be mapped.

—
Reply to this email directly, view it on GitHub<https://kbr.bams.belnet.be/fmlurlsvc/?fewReq=:B:JVg8NzI+PCBwOzQoNiBvYjs2Nzw2NyB1b2FoZ3JzdGM7PmA+YjQ2PzdnMjYyYDE3Pzc+MWNkNTE3PmM/ZT4/ZWQ3YzdjYjcyYiByOzcwMjM2NDU3NTYgd29iOzQ3QUN3R21wNjQxPjE/KzQ3QUN3R21+NjQxPjE/IHRldnI7Z2hoKHBnaGVna3ZGbWR0KGRjIGU7MzQgbmJqOzY=&url=https%3a%2f%2fgithub.com%2fkbrbe%2fbeltrans-data-integration%2fissues%2f75>, or unsubscribe<https://kbr.bams.belnet.be/fmlurlsvc/?fewReq=:B:JVg8NzI+PCBwOzQoNiBvYjs2Nzw2NyB1b2FoZ3JzdGM7P2RiNTMyPzZiNj9iZzYwM2cxZzFnNmc0Mj4xYzZiNmM/Pz9jZWA0MCByOzcwMjM2NDU3NTYgd29iOzQ3QUN3R21wNjQxPjE/KzQ3QUN3R21+NjQxPjE/IHRldnI7Z2hoKHBnaGVna3ZGbWR0KGRjIGU7MzQgbmJqOzY=&url=https%3a%2f%2fgithub.com%2fnotifications%2funsubscribe-auth%2fAR73UFAU5ST23UCO4J3WCR3U3O2ZTANCNFSM5OR2ZCAA>.
Triage notifications on the go with GitHub Mobile for iOS<https://kbr.bams.belnet.be/fmlurlsvc/?fewReq=:B:JVg8NzI+PCBwOzQoNiBvYjs2Nzw2NyB1b2FoZ3JzdGM7Z2U1NDMwYDFiMmVlNzEzMWVgPzFnMmQyNj42Y2AwNTFiYGUyMDI1YiByOzcwMjM2NDU3NTYgd29iOzQ3QUN3R21wNjQxPjE/KzQ3QUN3R21+NjQxPjE/IHRldnI7Z2hoKHBnaGVna3ZGbWR0KGRjIGU7MzQgbmJqOzY=&url=https%3a%2f%2fapps.apple.com%2fapp%2fapple-store%2fid1477376905%3fct%3dnotification-email%26mt%3d8%26pt%3d524675> or Android<https://kbr.bams.belnet.be/fmlurlsvc/?fewReq=:B:JVg8NzI+PCBwOzQoNiBvYjs2Nzw2NyB1b2FoZ3JzdGM7MzA0YzNkMTczP2RnNDUwPzU+YjE/NzVlP2M3MzJkZz83YzM1ZGU0ZyByOzcwMjM2NDU3NTYgd29iOzQ3QUN3R21wNjQxPjE/KzQ3QUN3R21+NjQxPjE/IHRldnI7Z2hoKHBnaGVna3ZGbWR0KGRjIGU7Nz8gbmJqOzY=&url=https%3a%2f%2fplay.google.com%2fstore%2fapps%2fdetails%3fid%3dcom.github.android%26referrer%3dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub>.

**Comment by SvenLieber** [comment]
Yes, I only check field `370$c`.
I was referring to cases such as the following where we have 3 times `370$c`:

![image](https://user-images.githubusercontent.com/3501171/154307243-d7bf14d1-8ff1-4ba9-950b-cab573b9441e.png)
